Create 02-GUI-introduction.md
gitter-lab/ml-bio-workshop pull request #103
Opened 2020-09-26 22:16 UTC by cmilica

adding the software lesson. Using a lot of about ml4bio materials.

2020-09-30 14:48 UTC, agitter requested changes
This looks great overall. I have a few specific questions and comments.

Should we now delete the "A quick tour" section from the "About ml4bio software" page?

2020-09-30 14:48 UTC, agitter commented on _episodes/02-GUI-introduction.md
> +- What is ml4bio software?
```suggestion
- What is the ml4bio software?
```

2020-09-30 14:48 UTC, agitter commented on _episodes/02-GUI-introduction.md
> +-
```suggestion
- The ml4bio software supports interactively exploring different classifiers and hyperparmaters on a dataset
```

2020-09-30 14:48 UTC, agitter commented on _episodes/02-GUI-introduction.md
> +Load *toy_data_1.csv* file from the data/toy_data by clicking on **Select File...**.
Should we use the Software callout formatting that is used in later lessons here and in later steps?

2020-09-30 14:48 UTC, agitter commented on _episodes/02-GUI-introduction.md
> +## Practice to Use the Software in Small Groups
This part is very good.  It will help a lot for later lessons to get practice.

2020-09-30 14:48 UTC, agitter commented on _episodes/02-GUI-introduction.md
> +Either pick your own classifier you would like to test,
Should we ask them to share the performance they get within the group?  Or with everyone?

2020-09-30 14:48 UTC, agitter commented on _episodes/02-GUI-introduction.md
> +exercises: 5
I think we'll need to budget more time for this lesson.

2020-10-13 00:07 UTC, cmilica commented on _episodes/02-GUI-introduction.md
> +- What is ml4bio software?
Yes, I think we should probably delete that part!

2020-10-13 00:08 UTC, cmilica commented on _episodes/02-GUI-introduction.md
> +exercises: 5
probably - you think 30 min?

2020-10-13 00:15 UTC, cmilica commented on _episodes/02-GUI-introduction.md
> +Load *toy_data_1.csv* file from the data/toy_data by clicking on **Select File...**.
I was wondering about that part - the reason I didn't add it originally, I thought it might be too much text in the callout boxes. But we can see how it looks, and always change it back. I will add it!

2020-10-13 00:16 UTC, cmilica commented on _episodes/02-GUI-introduction.md
> +Either pick your own classifier you would like to test,
yes, that would be good. Maybe with everyone?

2020-10-14 12:57 UTC, agitter commented on _episodes/02-GUI-introduction.md
> +Either pick your own classifier you would like to test,
Maybe we have them first share with a partner or small group and then ask 2-3 groups to share their best?

2020-10-14 12:57 UTC, agitter commented on _episodes/02-GUI-introduction.md
> +exercises: 5
Yes, 15 teaching and 15 exercises seems about right.

2020-10-14 14:52 UTC, cmilica commented on _episodes/02-GUI-introduction.md
> +Either pick your own classifier you would like to test,
I think that would be the best.

2021-01-27 04:25 UTC, cmilica commented on _episodes/02-GUI-introduction.md
> +Load *toy_data_1.csv* file from the data/toy_data by clicking on **Select File...**.
I added the boxes, check it out if it looks ok!

2021-01-27 04:25 UTC, cmilica commented on _episodes/02-GUI-introduction.md
> +Either pick your own classifier you would like to test,
done! Let me know if it makes sense !

2021-01-28 17:54 UTC, agitter reviewed
Thanks for the updates.  This is looking very close to being ready to merge.

I edited two other files to remove the duplicate instructions and hopefully link to this lesson from the about page.  We'll have to check the link worked after merging.

I suggested some additional text changes.  If they look good, you can use the `Commit suggestion` button to make those changes.

2021-01-28 17:54 UTC, agitter commented on _episodes/02-GUI-introduction.md
> +title: "GUI Introduction"
```suggestion
title: "ml4bio Software Introduction"
```
I don't expect our participants will know the acronym GUI.

2021-01-28 17:54 UTC, agitter commented on _episodes/02-GUI-introduction.md
> +The last page is for testing and prediction (steps 6 and 7).
```suggestion
The first page allows you to load data, split data and choose a validation method.
The second page is where you train classifiers.
The last page is for testing and prediction.
```

Our steps are no longer numbered 1-7.

2021-01-28 17:54 UTC, agitter commented on _episodes/02-GUI-introduction.md
> +<img width="350" src="{{ page.root }}/fig/software/before_load.png">
If these image paths no longer work, I can fix them after we merge.  We'll need to remember to check that.

2021-01-28 17:54 UTC, agitter commented on _episodes/02-GUI-introduction.md
> +> Load *toy_data_1.csv* file from the data/toy_data by clicking on **Select File...**.
Are we doing to have the participants watch the instructors do this and then have them follow the instructions to do ti themselves?

2021-01-28 17:54 UTC, agitter commented on _episodes/02-GUI-introduction.md
> +
```suggestion
The classifier's overall precision on the training data is 0.9.
These evaluation metrics will be discussed later in the workshop.
For now, all you need to know is that in general higher numbers indicate better performance.

```

2021-01-28 17:54 UTC, agitter commented on _episodes/02-GUI-introduction.md
> +## Practice to Use the Software in Small Groups
```suggestion
## Practice Using the Software in Small Groups
```

2021-01-28 17:54 UTC, agitter commented on _episodes/02-GUI-introduction.md
> +From the *data/toy_data* select *toy_data_4.csv*.
Should this instruction and the ones below have the software callout formatting?

2021-01-28 17:54 UTC, agitter commented on _episodes/02-GUI-introduction.md
> +Either pick your own classifier you would like to test,
Yes, this is good.

2021-02-02 16:45 UTC, cmilica commented on _episodes/02-GUI-introduction.md
> +> Load *toy_data_1.csv* file from the data/toy_data by clicking on **Select File...**.
Is this something that we might have to edit once we start run-throughs?

2021-02-02 16:46 UTC, cmilica commented on _episodes/02-GUI-introduction.md
> +From the *data/toy_data* select *toy_data_4.csv*.
Yes, probably. I definitely could've missed some of the software callouts. I'll edit this.

2021-02-02 19:11 UTC, agitter commented on _episodes/02-GUI-introduction.md
> +> Load *toy_data_1.csv* file from the data/toy_data by clicking on **Select File...**.
Yes, let's figure that out once we start practicing the online format.

2021-02-02 19:13 UTC, agitter approved these changes
Thanks for the updates.  I'm going to merge this so we can check whether the links and images all work.  We can open a new pull request if we find more things to change.

2021-02-02 19:13 UTC, merged

2021-02-02 19:21 UTC, agitter commented on _episodes/02-GUI-introduction.md
> +<img width="350" src="{{ page.root }}/fig/software/before_load.png">
The images render correctly after merging.  There was an error in a link that I fixed in 704c8692d7cc974096583fcd91cf0f0fc5718538